setopt append_history
setopt auto_cd
setopt no_extended_glob
setopt no_match
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt hist_ignore_all_dups
setopt inc_append_history
setopt multios
setopt prompt_subst
setopt share_history

